### ISSUE TITLE
Upper case letter issues.

### ISSUE THREAD

**Issue by ashtonneth** [roge123789/landing#18]
When we edit any letter in lower case then why its look in Upper case.(Also in the knowledge of Sourabh Sir)

**Comment by roge123789** [comment]
Can you please provide  the screen shot of the area where you are facing above issue ?

**Comment by ashtonneth** [comment]
This error will occur in all the headings and screen Shot.
![a11](https://cloud.githubusercontent.com/assets/25498661/24650987/b66c280a-1949-11e7-9b08-8ec0f06c660e.png)

**Comment by roge123789** [comment]
I have changed the text case from UPPER CASE to user defined case
