### ISSUE TITLE
Link not edited some times.

### ISSUE THREAD

**Issue by ashtonneth** [roge123789/landing#20]
Keep the issues correct .
![wpl22](https://cloud.githubusercontent.com/assets/25498661/24148544/51935e42-0e65-11e7-8e60-f6fba7a1d219.png)

**Comment by roge123789** [comment]
Can you specify on which module you face this issue.

**Comment by roge123789** [comment]
issue with complete template

**Comment by roge123789** [comment]
i have fixed this issue you can review it on http://wplpage.newsoftdemo.info/wp-admin/admin.php?page=wp-landing&id=43

**Comment by ashtonneth** [comment]
Sometimes it doesn,t edit.
