### ISSUE TITLE
13.Why plugin css/js loaded on other pages of wordpress admin, Speed Slow. When we take any custom field it seems fine but in another field its not coming from same folder.

### ISSUE THREAD

**Issue by ashtonneth** [roge123789/landing#4]
When we take any custom field it seems fine but in another field its not coming from same folder.
![13point](https://cloud.githubusercontent.com/assets/25498661/22581021/0d9c904a-ea03-11e6-9cfb-747091cfc6e8.png)

**Comment by roge123789** [comment]
i have checked that the js/css working only plugin part
